title: Unitest status
buildFuture: true
defaultContentLanguage: fr
languageCode: fr
baseURL: https://status.arthurd.fr
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: true
  shortDateFormat: 15:04 UTC — 2 Jan
  down: "#e60000"
  systems:
    - name: FTTH
      category: Collecte
    - name: FTTH Pro
      category: Collecte
    - name: ADSL
      category: Collecte
    - name: SDSL
      category: Collecte
    - name: 4G
      category: Collecte
    - name: Serveur DNS
      category: Hébergement
      description: Hébergement des zones DNS
    - name: Uniservice
      category: Hébergement
      description: Serveur mail
      partial: ""
    - category: Hébergement
      name: Web01
      description: Hébergement web mutualisé
    - name: Web02
      category: Hébergement
      description: Hébergement web mutualisé
    - name: Web03
      category: Hébergement
      description: Hébergement web mutualisé
    - name: VPS
      category: Hébergement
      description: Hébergement de machine virtuelle
      partial: ""
  dateFormat: 2 January, 2006 at 3:04 UTC
  brand: "#FFFFFF"
  enableLastMod: true
  headerTextColor: white
  logo: https://www.kindpng.com/picc/m/287-2876952_beta-testing-banner-adults-only-logo-png-transparent.png
  incidentPostsPerPage: 1
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: true
  ok: "#008000"
  categories:
    - name: Collecte
      description: ""
      closed: true
    - name: Hébergement
      closed: true
  description: Nous surveillons en permanence l'état de nos services. En cas de
    perturbation d'un ou plusieurs service(s), une note sera affichée ici.
  enableCustomHTML: false
  useLargeHeaderDesign: false
